src/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [

	path('register/', views.register, name='register'),
	path('login/', views.login, name='login'),
	path('logout/', views.logout_user, name='logout'),
	path('activate/<uidb64>/<token>/', views.activate, name='activate'),
	path('dashboard/', views.dashboard, name='dashboard'),

	
	path('forgot_password/', views.forgot_password, name='forgot_password'),
	path('reset_password/', views.reset_password, name='reset_password'),
	path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),

]

src/alishop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('store/', include('store.urls')),
    path('carts/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    # path('tinymce/', include('tinymce.urls')), 
    # path('ckeditor/', include('ckeditor_uploader.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [

	path('', views.cart, name='carts'),
	path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
	path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
	path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

	path('checkout/', views.checkout, name='checkout'),
	
]

src/store/urls.py
from django.urls import path
from . import views

app_name = 'store'


urlpatterns = [

	path('', views.store, name='shop'),
	path('search/', views.search, name='search'),
	path('category/<slug:category_slug>/', views.store, name='product_by_category'),
	path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
]

src/templates/base/_header.html
{% load static %}

<header class="section-header">

	{% if 'store' in request.path %}

	  {% include "includes/store_nav_section.html" %}

	{% else %}

		<nav class="navbar d-none d-md-flex p-md-0 navbar-expand-sm navbar-light border-bottom">
			<div class="container">
			  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			    <span class="navbar-toggler-icon"></span>
			  </button>
			  <div class="collapse navbar-collapse" id="navbarTop4">

			  		{% include "includes/authentication.html" %}

				    <ul class="navbar-nav">
						<li><a href="{% url 'store:shop' %}" class="nav-link"> Store</a></li>
						<li><a href="#" class="nav-link"> <i class="fa fa-bell"></i> </a></li>
						<li><a href="#" class="nav-link"> <i class="fa fa-shopping-cart"></i> </a></li>
					</ul> <!-- list-inline //  -->
			  </div> <!-- navbar-collapse .// -->
			</div> <!-- container //  -->
		</nav>

	{% endif %}

<div class="container">
	<section class="header-main border-bottom">
		<div class="row row-sm">
			<div class="col-6 col-sm col-md col-lg  flex-grow-0">
				<a href="{% url 'home' %}" class="brand-wrap">
					<img class="logo" src="{% static 'images/logo.svg' %}">
				</a> <!-- brand-wrap.// -->
			</div>
			<div class="col-6 col-sm col-md col-lg flex-md-grow-0">

				<!-- mobile-only -->
				<div class="d-md-none float-right">
					{% comment %}
						<a href="#" class="btn btn-light"> <i class="fa fa-bell"></i> </a>
					{% endcomment %}
					<a href="/" class="btn btn-light"> <i class="fa fa-user"></i> </a>
					<a href="#" class="btn btn-light"> <i class="fa fa-shopping-cart"></i> 2 </a>
				</div>
				<!-- mobile-only //end  -->

				<div class="category-wrap d-none dropdown d-md-inline-block">
					<button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown">   Trier par
					</button>
					<div class="dropdown-menu">
						{% for categorie in  categories %}
						<a class="dropdown-item" href="#">{{ categorie.category_name|capfirst }}</a>
						{% endfor %}
					</div>
				</div>  <!-- category-wrap.// -->
			</div> <!-- col.// -->

			{% comment %}
				
			<div class="col-lg-6 col-xl col-md-5 col-sm-12 flex-grow-1">
				<form action="#" class="search-header">
					<div class="input-group">
					    <input type="text" class="form-control" placeholder="Chercher">
				    </div>
				</form> 
			</div> 

			{% endcomment %}

			<div class="col-xl-6 col-lg-5 col-md-6">
				<form action="#" class="search-header">
					<div class="input-group w-100">
					    <input type="text" class="form-control" placeholder="Chercher">
					    
					    <div class="input-group-append">
					      <button class="btn btn-primary" type="submit">
					        <i class="fa fa-search"></i>
					      </button>
					    </div>
				    </div>
				</form> <!-- search-wrap .end// -->
			</div> <!-- col.// -->

<!-- 			<div class="col col-lg col-md flex-grow-0">
			    <button class="btn btn-block btn-light" type="submit"> Advanced </button>
			</div> -->
		</div> <!-- row.// -->
	</section> <!-- header-main .// -->




{% include "includes/navbar_main.html" %}


</div> <!-- container.// -->
</header> <!-- section-header.// -->

src/templates/base/base.html
{% load static %}
{% load humanize %}
<!DOCTYPE HTML>
<html lang="fr">
<head>
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>

	Makeety | 

	{% block title %}
		
	{% endblock title %}


</title>

<link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">

<!-- jQuery -->
<script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'css/responsive.css' %}" rel="stylesheet" type="text/css" />

<!-- custom javascript -->
<script src="{% static 'js/script.js' %}" type="text/javascript"></script>

</head>
<body>

	{% include "base/header.html" %}



	{% block content %}
		



	{% endblock content %}




	{% include "includes/footer.html" %}
</body>
</html>

src/templates/base/header.html
{% load static %}


	<header class="section-header">
		<section class="header-main border-bottom">
			<div class="container">
				<div class="row align-items-center">
					<div class="col-xl-2 col-lg-3 col-md-12">
						<a href="{% url 'home' %}" class="brand-wrap">
							<img class="logo" src="{% static 'images/logo.png' %}">
						</a> <!-- brand-wrap.// -->
					</div>
					<div class="col-xl-6 col-lg-5 col-md-6">
						<form action="{% url 'store:search' %}" class="search-header" method="GET" required="required">
							<div class="input-group w-100">

								<input type="text" class="form-control" placeholder="rechercher" name="q" required="required">

								<div class="input-group-append">
									<button class="btn btn-primary" type="submit">
										<i class="fa fa-search"></i> Rechercher
									</button>
								</div>
							</div>
						</form> <!-- search-wrap .end// -->
					</div> <!-- col.// -->
					<div class="col-xl-4 col-lg-4 col-md-6">
						<div class="widgets-wrap float-md-right">


							
							{% if request.user.is_authenticated %}

							<div class="widget-header mr-3">
								<a href="{% url 'accounts:logout' %}" class="widget-view">
									<div class="icon-area">
										<i class="fa fa-user"></i>
										<span class="notify">3</span>
									</div>
									<small class="text">Profil </small>
								</a>
							</div>

							<div class="widget-header mr-3">
								<a href="{% url 'carts:carts' %}" class="widget-view">
									<div class="icon-area">
										<i class="fa fa-shopping-cart"></i>
									<span class="notify">{{ cart_count }}</span>
									</div>
									<small class="text"> Panier </small>
								</a>
							</div>

							{% else %}

							<div class="widget-header mr-3">
								<a 
								
								{% if 'accounts:register' in request.path %}
								  class = "widget-view active"
								{% else %}
								  class = "widget-view"
								{% endif %}	

								href="{% url 'accounts:register' %}" >
									<div class="icon-area">
										<i class="fa fa-user-plus"></i>
									</div>
									<small class="text" title="S'inscrire"> S'inscrire ici </small>
								</a>
							</div>

							<div class="widget-header mr-3">
								<a href="{% url 'accounts:login' %}" class="widget-view">
									<div class="icon-area">
										<i class="fas fa-sign-in-alt" ></i>
									</div>
									<small class="text" title="Se connecter">Se connecter </small>
								</a>
							</div>

							  
							{% endif %}

							<div class="widget-header mr-3">
								<a

								{% if 'store' in request.path %}
									class="widget-view active"
								{% else %}
									class="widget-view"
								{% endif %}

								 href="{% url 'store:shop' %}" >
									<div class="icon-area">
										<i class="fa fa-store"></i>
									</div>
									<small class="text"> Store </small>
								</a>
							</div>
							

						</div> <!-- widgets-wrap.// -->
					</div> <!-- col.// -->
				</div> <!-- row.// -->
			</div> <!-- container.// -->
		</section> <!-- header-main .// -->

<!-- 
		<nav class="navbar navbar-main navbar-expand-lg border-bottom">
			<div class="container">
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav"
					aria-controls="main_nav" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="main_nav">
					<ul class="navbar-nav">

						{% for categorie in categories %}
							
						<li class="nav-item">
							<a class="nav-link" href="{{ categorie.get_url }}">{{ categorie.category_name|safe|capfirst }}</a>
						</li>

						{% endfor %}


					</ul>


				</div>
			</div> 
		</nav> -->
	</header> 

src/templates/base/mainsection.html
{% load static %}

<!-- ========================= SECTION MAIN  ========================= -->
<section class="section-intro padding-y">
<div class="container">
<!-- ==============  COMPONENT SLIDER  BOOTSTRAP ============  -->
<div id="carousel1_indicator" class="slider-home-banner carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carousel1_indicator" data-slide-to="0" class="active"></li>
    <li data-target="#carousel1_indicator" data-slide-to="1"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{{ banner_image1.image1.url }}" alt="First slide"> 
    </div>
    <div class="carousel-item">
      <img src="{{ banner_image2.image2.url }}" alt="Second slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carousel1_indicator" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel1_indicator" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div> 
<!-- ============ COMPONENT SLIDER BOOTSTRAP end.// ===========  .// -->	
	
</div> <!-- container end.// -->
</section>
<!-- ========================= SECTION MAIN END// ========================= -->