src/alishop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('store/', include('store.urls')),
    path('carts/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    # path('tinymce/', include('tinymce.urls')), 
    # path('ckeditor/', include('ckeditor_uploader.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [

	path('', views.cart, name='carts'),
	path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
	path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
	path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

	path('checkout/', views.checkout, name='checkout'),
	
]

src/store/urls.py
from django.urls import path
from . import views

app_name = 'store'


urlpatterns = [

	path('', views.store, name='shop'),
	path('search/', views.search, name='search'),
	path('category/<slug:category_slug>/', views.store, name='product_by_category'),
	path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
]

src/store/models.py
from django.db import models
from category.models import Category
from django.shortcuts import reverse, render
from datetime import datetime
# from tinymce.models import HTMLField
# from tinymce import models as tinymce_models
# Create your models here.
class Product(models.Model):

    features_choices=(
		('Cruise Control', 'Cruise Control'),
		('Audio Interface', 'Audio Interface'),
		('Airbags', 'Airbags'),
		('Air Conditioning', 'Air Conditioning'),
		('Seat Heating', 'Seat Heating'),
		('Alarm System', 'Alarm System'),
		('ParkAssist', 'ParkAssist'),
		('Power Steering', 'Power Steering'),
		('Reversing Camera', 'Reversing Camera'),
		('Direct Fuel Injection', 'Direct Fuel Injection'),
		('Auto Start/Stop', 'Auto Start/Stop'),
		('Wind Deflector', 'Wind Deflector'),
		('Bluetooth Handset', 'Bluetooth Handset'),
    )


    state_choice = (
        ('GN', 'GUINEE'),
        ('US', 'USA'),
        ('FR', 'FRANCE'),
        ('MA', 'MAROC'),
        ('CA', 'CANADA'),
        ('BR', 'BRESIL'),
        ('AR', 'ARGENTINE'),
        ('DE', 'ALLEMAGNE'),
        ('IT', 'ITALIE'),
        ('ES', 'ESPAGNE'),
        ('PT', 'PORTUGAL'),
        ('RU', 'RUSSIE'),
        ('IN', 'INDE'),
        ('ID', 'INDONESIE'),
        ('IN', 'Indiana'),
        ('MY', 'MALAYSIE'),
        ('CN', 'CHINE'),
        ('JP', 'JAPON'),
        ('UK', 'ANGLETERRE'),
        ('NL', 'PAYS BAS'),
        ('BE', 'BELGIQUE'),
    )



    condition_choice = (

    	('New', 'New'),

    )

    year_choice = []

    for r in range(2000, (datetime.now().year+1)):
    	year_choice.append((r,r))

    product_name  = models.CharField(max_length=200, verbose_name="Article")
    slug          = models.SlugField(max_length=200)
    description   = models.TextField()
    manufacturer  = models.CharField(choices=state_choice, max_length=50, blank=True, verbose_name='Fabricant')
    condition     = models.CharField(choices=condition_choice, max_length=200, blank=True)
    year          = models.IntegerField(('Année'), choices=year_choice, default='2021')
    price         = models.IntegerField(verbose_name='Prix', default=0)
    category      = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Categorie de l\'article', related_name='categorie')
    features      = models.CharField(choices=features_choices, blank=True, verbose_name='Caracteristiques', max_length=200)
    specification = models.TextField(blank=True, null=True)
    image         = models.ImageField()
    image1        = models.ImageField(blank=True)
    image2        = models.ImageField(blank=True)
    image3        = models.ImageField(blank=True)
    image4        = models.ImageField(blank=True)
    stock         = models.IntegerField(default=0)
    is_available  = models.BooleanField(default=True, verbose_name='Disponible ?')
    free_shipping = models.BooleanField(default=False, verbose_name='Livraison gratuite ?')
    created_date  = models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")
    modified_date = models.DateTimeField(auto_now=True,verbose_name='Modifié le')

    class Meta:
    	ordering = ['-created_date']
    	verbose_name = 'Article'
    	verbose_name_plural = 'Articles'

    def get_url(self):
    	return reverse('store:product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
    	return self.product_name


class Banner(models.Model):
    image1 = models.ImageField(upload_to='banner/images')
    image2 = models.ImageField(upload_to='banner/images')

    class Meta:
        verbose_name = "Bannière"
        verbose_name_plural = "Bannières"



class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='couleur', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='taille', is_active=True)

variation_category_choice = (
    ('couleur', 'couleur'),
    ('taille', 'taille'),
)

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Article")
    variation_category = models.CharField(max_length=100, choices=variation_category_choice, verbose_name="Caracteristiques")
    variation_value     = models.CharField(max_length=100, verbose_name="valeur de la caracteristique")
    is_active           = models.BooleanField(default=True, verbose_name="Deja active ?")
    created_date        = models.DateTimeField(auto_now=True, verbose_name="Date de creation")

    objects = VariationManager()

    def __str__(self):
        return self.variation_value

src/carts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from store.models import Product, Variation
from .models import Cart, CartItem
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
# Creation d'une session (id) associée à un panier
def _cart_id(request):

	cart = request.session.session_key

	if not cart:
		cart = request.session.create()

	return cart


# panier
# def cart(request, total=0, quantity=0, cart_items=None):
	
# 	try:

# 		tax = 0 
# 		grand_total = 0
# 		cart = Cart.objects.get(cart_id=_cart_id(request))
# 		cart_items = CartItem.objects.filter(cart=cart, is_active=True)

# 		for cart_item in cart_items:

# 			total += (cart_item.product.price * cart_item.quantity)
# 			quantity += cart_item.quantity

# 		tax = (2 * total) / (100)
# 		grand_total = total + tax

# 	except ObjectDoesNotExist:
# 		pass

# 	context = {

# 		'total': total,
# 		'quantity' : quantity,
# 		'cart_items' : cart_items,
# 		'taxt'		 : tax,
# 		'grand_total': grand_total,
# 	}

# 	template_name = 'store/cart.html'

# 	return render(request, template_name, context)

def cart(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total)/100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass #just ignore

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax'       : tax,
        'grand_total': grand_total,
    }
    return render(request, 'store/cart.html', context)



# ajouter un article à un panier



def add_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id) #get the product
    # If the user is authenticated
    if current_user.is_authenticated:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass


        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, user=current_user)
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            if product_variation in ex_var_list:
                # increase the cart item quantity
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()

            else:
                item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                #cart=_cart_id(request), # point d'arrêt
                user = current_user,
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('carts:carts')

    else:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass
        try:
            cart = Cart.objects.get(cart_id=_cart_id(request)) # get the cart using the cart_id present in the session
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id = _cart_id(request)
            )
        cart.save()

        is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            # existing_variations -> database
            # current variation -> product_variation
            # item_id -> database
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            # print(ex_var_list)

            if product_variation in ex_var_list:
                # increase the cart item quantity
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()

            else:
                item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                cart = cart,
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('carts:carts')





# décrementer la quantité d'un article
# def remove_cart(request, product_id):

# 	cart = Cart.objects.get(cart_id=_cart_id(request))
# 	product = get_object_or_404(Product, id=product_id)
# 	cart_item = CartItem.objects.get(product=product, cart=cart)

# 	if cart_item.quantity > 1:
# 		cart_item.quantity -= 1
# 		cart_item.save()
# 	else:
# 		cart_item.delete()

# 	return redirect('carts:carts')




# retirer un article du panier
def remove_cart(request, product_id, cart_item_id):

    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('carts:carts')



def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('carts:carts')



def checkout(request):

	template_name = 'carts/checkout.html'
	context = {
	
	}

	return render(request, template_name, context)

src/store/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product
from category.models import Category
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.db.models import Q
# Create your views here.


def store(request, category_slug=None):

	categories = None
	product = None
	# new,  most_recent_categories = custom_function(Product)
	most_recent_categories = Category.objects.all()[:3]


	if category_slug:
		categories = get_object_or_404(Category, slug=category_slug)
		product = Product.objects.filter(is_available=True, category=categories)
		paginator = Paginator(product, 4)
		page = request.GET.get('page')
		paged_products = paginator.get_page(page)
		product_count = product.count()
	else:
		product = Product.objects.all().filter(is_available=True).order_by('id')
		paginator = Paginator(product, 4)
		page = request.GET.get('page')
		paged_products = paginator.get_page(page)
		product_count = product.count() 

	template_name = 'store/store.html'
	context = {
		'most_recent_categories':most_recent_categories,
		'available_product': paged_products,
		'product_count': product_count,
		# 'new' : new,

	}

	return render(request, template_name, context)


def product_detail(request, category_slug, product_slug):

	try:
		single_product = Product.objects.get(category__slug=category_slug, slug=product_slug)
	except Exception as e:
		raise e
	else:
		pass
	finally:
		pass

	template_name = 'store/product_detail.html'
	context = {
		'single_product':single_product,
	}

	return render(request, template_name, context)


def search(request):

	# new, used, old, most_recent_categories = custom_function(Product)
	products = None
	product_count=0

	# if products is None:
	# 	return HttpResponseRedirect()

	if 'q' in request.GET:
		keyword = request.GET['q']
		if keyword:
			products = Product.objects.order_by('-created_date').filter(Q(description__icontains=keyword) | Q(product_name__icontains=keyword) | Q(description__iexact=keyword) | Q(category__category_name__icontains=keyword) | Q(category__description__iexact=keyword) )
			product_count = products.count()

	template_name = 'store/store.html'
	context = {
		'available_product' : products,
		'product_count' : product_count,
		# 'most_recent_categories':most_recent_categories,
		# 'old':old,
		# 'new':new,
		# 'used':used,
	}

	return render(request, template_name, context)

src/templates/store/cart.html
{% extends "base/base.html" %}

{% load static %}

{% block title %}
	Panier
{% endblock title %}


{% block content %}
<!-- START -->
	<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
	<div class="container">

		{% if cart_items %}


		<div class="row">
			<main class="col-md-9">
				<div class="card">

					<div class="table-responsive">
					 <table class="table table-borderless table-shopping-cart">
						<thead class="text-muted">
						<tr class="small text-uppercase">
						  <th scope="col">Article</th>
						  <th scope="col" width="120">Quantité</th>
						  <th scope="col" width="120">Prix</th>
						  <th scope="col" class="text-right" width="200"> </th>
						</tr>
						</thead>
						<tbody>

							{% for cart_item in cart_items  %}
								
							<tr>
								<td>
									<figure class="itemside">
										<div class="aside">
											<a href="{{ cart_item.product.get_url }}">
											<img src="{{ cart_item.product.image.url }}" class="img-sm">
											</a>
										</div>
										<figcaption class="info">
											<a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.product_name|safe }}</a>
											<p class="text-muted small">
												{% if cart_item.variations.all %}
													{% for item in cart_item.variations.all  %}
														{{ item.variation_category | lower }} {{ item.variation_value | lower }} <br>
													{% endfor %}
												{% endif %}
											</p>
										</figcaption>
									</figure>
								</td>
								<td> 
		                		<div class="form-group col-md flex-grow-0">
		                			<div class="input-group mb-3 input-spinner">
		                			  <div class="input-group-prepend">
		                			    <a class="btn btn-light" type="button" id="button-minus" href="{% url 'carts:remove_cart' cart_item.product.id cart_item.id %}"> &minus;  </a>
		                			  </div>
		                			  <input type="text" class="form-control" value="{{ cart_item.quantity }}">
		                			  <div class="input-group-append">
		                			  <form action="{% url 'carts:add_cart' cart_item.product.id %}">
		                			  	{% csrf_token %}

		                			  	{% for item in cart_item.variations.all  %}

		                			  	<input type="hidden" name="{{ item.variation_category | lower }}" value="{{ item.variation_value | capfirst }}">

		                			  	{% endfor %}


		                			    <button class="btn btn-light" type="submit" id="button-plus" href=""> + </button>


		                			    </form>
		                			  </div>
		                			</div>
		                		</div> <!-- col.// -->
								</td>
								<td> 
									<div class="price-wrap"> 
										<var class="price"><small>{{ cart_item.sub_total|floatformat:2 }} <small>GNF</small></small></var> 
										<small class="text-muted">{{ cart_item.product.price|floatformat:2 }} <small>GNF</small> </small> 
									</div> <!-- price-wrap .// -->
								</td>
								<td class="text-right"> 
								<a href="{% url 'carts:remove_cart_item' cart_item.product.id cart_item.id %}" class="btn btn-light" title="Retirer" onclick="return confirm('Êtes-vous sûr de bien vouloir retirer cet article du panier ?')"> <i class="fa fa-trash" ></i> </a>
								</td>
							</tr>

							{% endfor %}


						</tbody>
					 </table>
					</div>
<!-- 					<div class="card-body border-top">
						<a href="#" class="btn btn-primary float-md-right"> Make Purchase <i class="fa fa-chevron-right"></i> </a>
						<a href="{% url 'store:shop' %}" class="btn btn-light"> <i class="fa fa-chevron-left"></i> Continue shopping </a>
					</div> -->	
				</div> <!-- card.// -->
				<div class="alert alert-success mt-3">
					<p class="icontext"><i class="icon text-success fa fa-truck"></i> Livraison gratuite entre 1-2 semaines.</p>
				</div>
			</main> <!-- col.// -->

			<aside class="col-md-3">
				
				<div class="card">
					<div class="card-body">
							<dl class="dlist-align">
							  <dt>Total:</dt>
							  <dd class="text-right">{{ total|floatformat:2 }}gnf</dd>
							</dl>
							<dl class="dlist-align">
							  <dt>TVA:</dt>
							  <dd class="text-right">{{ taxt|floatformat:2 }}%</dd>
							</dl>
							<dl class="dlist-align">
							  <dt>Prix TTC:</dt>
							  <dd class="text-right  h5"><small>{{ grand_total|floatformat:2 }}</small></dd>
							</dl>
							<hr>
							<p class="text-center mb-3">
								<img src="{% static 'images/misc/payments.png' %}" height="26">
							</p>
							<a href="" class="btn btn-primary btn-block"> Commander</a>
                        	<a href="{% url 'store:shop' %}" class="btn btn-light btn-block">Continuer votre shopping</a>	
					</div>  
				</div> 
			</aside> 
		</div>


		{% else %}

		<div class="container">
			
		<h2 class="text-center">Votre panier est vide.</h2>
		<br>

		<div class="text-center">
			<a href="{% url 'store:shop' %}" class="btn btn-primary">Continuer l'achat</a>
		</div>
			
		</div>

		{% endif %}
	</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

<!-- ========================= SECTION PAYMENT AND REFUND POLICY  ========================= -->
<section class="section-name border-top padding-y">

	{% if cart_items %}
		
	<div class="container">
	<h6>Politique de paiement et de remboursement</h6>
	<p>{% lorem 4 p random %}</p>

	</div><!-- container // -->

	{% else %}
		

	<div class="container"></div>

	{% endif %}
</section>
<!-- ========================= SECTION  END// ========================= -->








<!-- END -->
{% endblock content %}

src/templates/store/product_detail.html
{% extends "base/base.html" %}

{% load static %}

{% block title %}
	{{ single_product.product_name|safe }}
{% endblock title %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content bg-white padding-y">
  	<div class="container">
		<form action="{% url 'carts:add_cart' single_product.id %}" method="POST">
			{% csrf_token %}
			<!-- ============================ ITEM DETAIL ======================== -->
			<div class="row">
					<aside class="col-md-6">
						<div class="card">
							<article class="gallery-wrap"> 
								<div class="img-big-wrap">
								<div> 
								<a href="{% url 'store:shop' %}">
									<img src="{{ single_product.image.url }}">
								</a>
								</div>
								</div> 
								<div class="thumbs-wrap">

									{% if single_product.image1 %}
								<a href=" {{single_product.product.get_url}} " class="item-thumb"> <img src=" {{single_product.image1.url}} "></a>
									{% endif %}

									{% if single_product.image2 %}
										<a href="{{single_product.product.get_url}} " class="item-thumb"> <img src="{{single_product.image2.url}}"></a> 
									{% endif %}
									
									
									{% if single_product.image3 %}		
								<a href="{{single_product.product.get_url}}" class="item-thumb"> <img src="{{ single_product.image3.url }}"></a>
									{% endif %}

									
									{% if single_product.image4 %}
								<a href="{{single_product.product.get_url}}" class="item-thumb"> <img src="{{ single_product.image4.url }}"></a>
									{% endif %}

								</div> 
							</article> 
						</div>
					</aside>
					<main class="col-md-6">
						<article class="product-info-aside">
							<h2 class="title mt-3">{{ single_product.product_name|safe }} </h2>
								<div class="rating-wrap my-3">
									<ul class="rating-stars">
										<li style="width:80%" class="stars-active"> 
											<i class="fa fa-star"></i> <i class="fa fa-star"></i> 
											<i class="fa fa-star"></i> <i class="fa fa-star"></i> 
											<i class="fa fa-star"></i> 
										</li>
										<li>
											<i class="fa fa-star"></i> <i class="fa fa-star"></i> 
											<i class="fa fa-star"></i> <i class="fa fa-star"></i> 
											<i class="fa fa-star"></i> 
										</li>
									</ul>
									<small class="label-rating text-muted">132 reviews</small>
									<small class="label-rating text-success"> <i class="fa fa-clipboard-check"></i> 154 orders </small>
								</div> 

								<div class="mb-3"> 
									<var class="price h4">{{ single_product.price|floatformat:2 }} GNF</var> 
									<!-- <span class="text-muted">£ 562.65 incl. VAT</span>  -->
								</div>

								<p>{{ single_product.description|safe }}</p>


								<dl class="row">
									<dt class="col-sm-3">Fabricant</dt>
									<dd class="col-sm-9"><a>{{ single_product.manufacturer|safe }}</a></dd>

									<dt class="col-sm-3">Article numéro</dt>
									<dd class="col-sm-9">596 065</dd>

									{% if single_product.free_shipping %}
										
									<dt class="col-sm-3">Livraison</dt>
									<dd class="col-sm-9">Oui</dd>

									{% endif %}


									<dt class="col-sm-3">Disponible</dt>

									{% if single_product.stock <= 0 or single_product.is_available == False %}

									<dd class="col-sm-9 text-danger"><strong>En rupture de stock</strong></dd>
									
									{% else %}

									<dd class="col-sm-9">En stock</dd>
									
									{% endif %}

								</dl>

									
								<div class="form-row  mt-4">
									
									{% if single_product.variation_set.colors and single_product.variation_set.sizes %}
										
									<div class="form-group col-md">
																			
										<select name="couleur" id="" class="form-control col-sm-3 col-md-4" required>
											<option value="" disabled selected>Couleur</option>
											{% for i in single_product.variation_set.colors  %}
												
											<option value="{{ i.variation_value | lower }}">{{ i.variation_value | safe | capfirst }}</option>

											{% endfor %}

										</select>
										<br>

										<select name="taille" id="" class="form-control col-sm-3 col-md-4" required>
											<option value="" disabled selected >Taille</option>
											{% for i in single_product.variation_set.sizes  %}
												
											<option value="{{ i.variation_value | lower }}">{{ i.variation_value | safe | capfirst }}</option>

											{% endfor %}
										</select>
										
									</div>

									{% endif %}


								</div> 

								{% if single_product.stock >= 1 or single_product.is_available != False %}


								<div class="form-group col-md">
										<button href=""  class="btn  btn-primary"> 
											<i class="fas fa-shopping-cart"></i> <span class="text">Ajouter au panier</span> 
										</button>
								</div>

							{% endif %}

						</article>
					</main> 
			</div> 

		</form>
      <!-- ================ ITEM DETAIL END .// ================= -->
	</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

<!-- ========================= SECTION  ========================= -->
<section class="section-name padding-y bg">
  <div class="container">
    <div class="row">
    	<div class="col-md-8">
    		<h5 class="title-description">Description</h5>
    		<p>
        {{ single_product.description|safe }}
    		</p>

    		{% if single_product.specification %}
    			
    		<h5 class="title-description">Specifications</h5>

    		{{ single_product.specification|safe }}

    		{% endif %}

    	</div> <!-- col.// -->
    	
    	<aside class="col-md-4">

    		<div class="box">
    		
    		<h5 class="title-description">Files</h5>
    			<p>
    				{% lorem p random %}
    			</p>

        <h5 class="title-description">Videos</h5>
          

        <article class="media mb-3">
          <a href="#"><img class="img-sm mr-3" src="{% static 'images/posts/3.jpg' %}"></a>
          <div class="media-body">
            <h6 class="mt-0"><a href="#">How to use this item</a></h6>
            <p class="mb-2"> Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin </p>
          </div>
        </article>

        <article class="media mb-3">
          <a href="#"><img class="img-sm mr-3" src="{% static 'images/posts/2.jpg' %}"></a>
          <div class="media-body">
            <h6 class="mt-0"><a href="#">New tips and tricks</a></h6>
            <p class="mb-2"> Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin </p>
          </div>
        </article>

        <article class="media mb-3">
          <a href="#"><img class="img-sm mr-3" src="{% static 'images/posts/1.jpg' %}"></a>
          <div class="media-body">
            <h6 class="mt-0"><a href="#">New tips and tricks</a></h6>
            <p class="mb-2"> Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin </p>
          </div>
        </article>


    		
    	</div> <!-- box.// -->
    	</aside> <!-- col.// -->
    </div> <!-- row.// -->
  </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock content %}