src/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [

	path('register/', views.register, name='register'),
	path('login/', views.login, name='login'),
	path('logout/', views.logout_user, name='logout'),
	path('activate/<uidb64>/<token>/', views.activate, name='activate'),
	path('dashboard/', views.dashboard, name='dashboard'),

	
	path('forgot_password/', views.forgot_password, name='forgot_password'),
	path('reset_password/', views.reset_password, name='reset_password'),
	path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),

]

src/alishop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('store/', include('store.urls')),
    path('carts/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    # path('tinymce/', include('tinymce.urls')), 
    # path('ckeditor/', include('ckeditor_uploader.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [

	path('', views.cart, name='carts'),
	path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
	path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
	path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),

	path('checkout/', views.checkout, name='checkout'),
	
]

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
# Create your models here.


class MyAccountManager(BaseUserManager):

	def create_user(self, first_name, last_name, username, email, password=None):

		if not email:
			raise ValueError('Vous devez fournir une adresse email')
		
		if not first_name:
			raise ValueError("Le nom d'utilisateur est requis.")

		user = self.model(

			email = self.normalize_email(email),
			username = username,
			first_name = first_name,
			last_name = last_name

			)

		user.set_password(password)
		user.save(using=self._db)


		return user


	def create_superuser(self, first_name, last_name, username, email, password):
		user = self.create_user(

			email = self.normalize_email(email),
			first_name = first_name,
			last_name = last_name,
			username = username,
			password = password,

			)

		user.is_active     = True
		user.is_admin      = True
		user.is_staff      = True
		user.is_superadmin = True

		user.save(using=self._db)

		return user





class Account(AbstractBaseUser):
	first_name = models.CharField(max_length=80, verbose_name='Nom')
	last_name  = models.CharField(max_length=80, verbose_name='Prenom')
	username   = models.CharField(max_length=80, unique=True, verbose_name="Nom d'utilisateur")
	email      = models.CharField(max_length=200, unique=True, verbose_name='Email')
	# phone      = models.CharField(max_length=20, verbose_name='Telephone')
	# phone      = PhoneNumberField()


	# required
	date_joined   = models.DateTimeField(auto_now_add=True, verbose_name='Compte crée')
	last_login    = models.DateTimeField(auto_now_add=True, verbose_name="Dernière connexion")
	is_admin      = models.BooleanField(default=False, verbose_name="admin ?")
	is_active     = models.BooleanField(default=False,verbose_name="Compte activé ?")
	is_staff      = models.BooleanField(default=False, verbose_name="Membre ?")
	is_superadmin = models.BooleanField(default=False, verbose_name="Super administrateur ?")

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

	objects = MyAccountManager()

	class Meta:
		verbose_name = 'compte utilisateur'
		verbose_name_plural = 'compte utilisateur'


	def __str__(self):
		return str(self.email)

	def has_perm(self, perm, obj=None):
		return self.is_admin

	def has_module_perms(self, add_label):
		return True

src/accounts/forms.py
from django import forms
from .models import Account

class RegistrationForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Mot de passe',
        'class': 'form-control',
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirmer votre mot de passe',
        'class'      : 'form-control',
    }))

    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'email', 'password']

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError(
                "Les mots de passe ne correspondent pas!"
            )

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Votre nom'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Votre prénom'
        # self.fields['phone'].widget.attrs['placeholder'] = 'Numéro de téléphone'
        self.fields['email'].widget.attrs['placeholder'] = 'Votre adresse email'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
        
    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password and confirm_password and password != confirm_password :
            raise forms.ValidationError("Les mots de passe doivent être identiques")

src/accounts/views.py
from django.shortcuts import render, redirect, reverse
from .forms import RegistrationForm
from .models import Account
from django.contrib import messages, auth
from django.contrib.auth.decorators  import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from carts.views import _cart_id
from carts.models import Cart, CartItem
import requests

# Connexion
def login(request):

    if request.user.is_authenticated:
        return redirect('home')
    
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = auth.authenticate(email=email, password=password)
        
        if user is not None:
            auth.login(request, user)
            messages.success(request, 'Nous sommes ravis de vous revoir.')
            return redirect('accounts:dashboard')
        else:
            messages.error(request, 'Votre adresse email ou votre mot de passe est incorrecte')
            return render(request, 'accounts/login.html')
    else:
        return render(request, 'accounts/login.html') 


# Déconnexion
@login_required(login_url = 'accounts:login')
def logout_user(request):
	auth.logout(request)
	messages.success(request, 'Vous êtes deconnecté.')
	return redirect('accounts:login')

# Inscription
def register(request):

    if request.user.is_authenticated:
        return redirect('home')
    else:

        if request.method == 'POST':
            form = RegistrationForm(request.POST)
            if form.is_valid():
                first_name   = form.cleaned_data['first_name']
                last_name    = form.cleaned_data['last_name']
                # phone        = form.cleaned_data['phone']
                email        = form.cleaned_data['email']
                password     = form.cleaned_data['password']
                username     = email.split('@')[0]
                user = Account.objects.create_user(first_name=first_name, last_name=last_name, email=email, username=username, password=password)
                # user.phone = phone
                user.save()

                # LIEN D'ACTIVATION DU COMPTE
                current_site = get_current_site(request)
                mail_subject = "Lien d'activation de votre compte"
                message      = render_to_string('accounts/account_verification_email.html', {
                    'user'   : user,
                    'domain' : current_site,
                    'uid'    : urlsafe_base64_encode(force_bytes(user.pk)),
                    'token'  : default_token_generator.make_token(user),
                    } )
                to_email=email
                send_email=EmailMessage(mail_subject, message, to=[to_email])
                send_email.send()
                # messages.success(request, "Compte crée avec succès")
                # return redirect('accounts:login')
                return redirect('/accounts/login/?command=verification&email='+email)

        else:
            form = RegistrationForm()

        context = {
        'form' : form,
        }
        return render(request, 'accounts/register.html', context)

# Lien d'activation du compte
def activate(request, uidb64, token):

    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Votre compte a bien été activé')
        return redirect('accounts:login')
    else:
        messages.error(request, 'Ce lien d\'activation a deja expiré.')
        return redirect('accounts:register')


# Dashboard
@login_required(login_url='accounts:login')
def dashboard(request):

    template_name = 'accounts/dashboard.html'
    context = {}

    
    return render(request, template_name, context)


# Réinitialiser le mot de passe
def forgot_password(request):

    if request.method == "POST":
        email = request.POST['email']
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email__exact=email)

            # LIEN D'ACTIVATION DU COMPTE
            current_site = get_current_site(request)
            mail_subject = "Réinitialisation de votre mot de passe"
            message      = render_to_string('accounts/reset_password_email.html', {
                'user'   : user,
                'domain' : current_site,
                'uid'    : urlsafe_base64_encode(force_bytes(user.pk)),
                'token'  : default_token_generator.make_token(user),
                } )
            to_email=email
            send_email=EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()
            messages.success(request, 'Un lien de réinitialisation de votre mot de passe vous a été envoyé ')
            return redirect('accounts:login')

        else:
            messages.error(request, 'Cette adresse email n\'est associée à aucun compte.')
            return redirect('accounts:forgot_password')


    template_name = 'accounts/forgot_password.html'
    context = {}
    
    return render(request, template_name, context)

def reset_password_validate(request, uidb64, token):

    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None
    
    if user is not None and default_token_generator.check_token(user, token):
        request.session['uid'] = uid
        messages.info(request, 'Entrez votre nouveau mot de passe')
        return redirect('accounts:reset_password')
    else:
        messages.error(request, 'Ce lien a déjà expiré')
        return redirect('accounts:forgot_password')

def reset_password(request):

    if request.method == 'POST':
        password = request.POST['password']
        password2 = request.POST['password2']

        if password == password2:
            uid = request.session.get('uid')
            user = Account.objects.get(pk=uid)
            user.set_password(password)
            user.save()
            messages.success(request, 'Votre mot de passe a été changé avec succès.')
            return redirect('accounts:login')

        else:
            messages.error(request, 'Les mots de passe ne sont pas identiques.')
            return redirect('accounts:reset_password')
    else:
        template_name = 'accounts/reset.html'
        context = {}
        
        return render(request, template_name, context)

src/templates/accounts/account_verification_email.html
{% autoescape off %}
Bonjour, {{user.first_name|capfirst}}

Veuillez cliquer sur ce lien pour finaliser votre inscription sur le site {{domain}}.

http://{{domain}}{% url 'accounts:activate' uidb64=uid token=token  %}
    
Si vous n'êtes pas à l'origine de cette action veuillez ignorer ce message.
{% endautoescape %}

src/templates/accounts/dashboard.html
{% extends "base/base.html" %}
{% load static %}


{% block title %}
    Dashboard
{% endblock title %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">

	{% include "includes/alerts.html" %}
	
<div class="container">

<div class="row">
	<aside class="col-md-3">
		<nav class="list-group">
			<a class="list-group-item" href="page-profile-main.html"> Account overview  </a>
			<a class="list-group-item" href="page-profile-address.html"> My Address </a>
			<a class="list-group-item active" href="page-profile-orders.html"> My Orders </a>
			<a class="list-group-item" href="page-profile-wishlist.html"> My wishlist </a>
			<a class="list-group-item" href="page-profile-seller.html"> My Selling Items </a>
			<a class="list-group-item" href="page-profile-setting.html"> Settings </a>
			<a class="list-group-item" href="{% url 'accounts:logout' %}">Quitter</a>
		</nav>
	</aside> <!-- col.// -->
	<main class="col-md-9">


		<article class="card order-item mb-4">
		<header class="card-header">
			<a href="#" class="float-right"> <i class="fa fa-print"></i> Print</a>
			<strong class="d-inline-block mr-3">Order ID: 6123456789</strong>
			<span>Order Date: 16 December 2018</span>
		</header>
		<div class="card-body">
			<div class="row"> 
				<div class="col-md-8">
					<h6 class="text-muted">Delivery to</h6>
					<p>Michael Jackson <br>  
					Phone +1234567890 Email: myname@pixsellz.com <br>
			    	Location: Home number, Building name, Street 123,  Tashkent, UZB <br> 
			    	P.O. Box: 100123
			 		</p>
				</div>
				<div class="col-md-4">
					<h6 class="text-muted">Payment</h6>
					<span class="text-success">
						<i class="fab fa-lg fa-cc-visa"></i>
					    Visa  **** 4216  
					</span>
					<p>Subtotal: $356 <br>
					 Shipping fee:  $56 <br> 
					 <span class="b">Total:  $456 </span>
					</p>
				</div>
			</div> <!-- row.// -->
		</div> <!-- card-body .// -->
		<div class="table-responsive">
		<table class="table table-hover">
			<tbody><tr>
				<td width="65">
					<img src="{% static 'images/items/1.jpg' %}" class="img-xs border">
				</td>
				<td> 
					<p class="title mb-0">Product name goes here </p>
					<var class="price text-muted">USD 145</var>
				</td>
				<td> Seller <br> Nike clothing </td>
				<td width="250"> <a href="#" class="btn btn-outline-primary">Track order</a>  
					<div class="dropdown d-inline-block">
						 <a href="#" data-toggle="dropdown" class="dropdown-toggle btn btn-outline-secondary">More</a>
						 <div class="dropdown-menu dropdown-menu-right">
						 	<a href="#" class="dropdown-item">Return</a>
						 	<a href="#"  class="dropdown-item">Cancel order</a>
						 </div>
					</div> <!-- dropdown.// -->
				</td>
			</tr>
			<tr>
				<td>
					<img src="{% static 'images/items/2.jpg' %}" class="img-xs border">
				</td>
				<td> 
					<p class="title mb-0">Another name goes here </p>
					<var class="price text-muted">USD 15</var>
				</td>
				<td> Seller <br> ABC shop </td>
				<td> <a href="#" class="btn btn-outline-primary">Track order</a>  
					<div class="dropdown d-inline-block">
						 <a href="#" data-toggle="dropdown" class="dropdown-toggle btn btn-outline-secondary">More</a>
						 <div class="dropdown-menu dropdown-menu-right">
						 	<a href="#" class="dropdown-item">Return</a>
						 	<a href="#"  class="dropdown-item">Cancel order</a>
						 </div>
					</div> <!-- dropdown.// -->
				</td>
			</tr>
		</tbody></table>
		</div> <!-- table-responsive .end// -->
		</article> <!-- card order-item .// -->


	</main> <!-- col.// -->
</div>

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock content %}
    

src/templates/accounts/forgot_password.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}
  Réinitialiser mot de passe
{% endblock title %}

{% block content %}
  
<section class="section-conten padding-y" style="min-height:84vh">

  
    <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
        <div class="card-body">
        <h4 class="card-title mb-4">Email de réinitialisation</h4>

        {% include "includes/alerts.html" %}
        
        <form method="POST" action="{% url 'accounts:forgot_password' %}">
          {% csrf_token %}
    

              <div class="form-group">
                  <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
                    </div>
                    <input type="email" name="email" class="form-control" placeholder="Votre adresse email" required="required">
                   </div>
              </div>  


            
            <div class="form-group">
              <a href="{% url 'accounts:login' %}" class="float-right">Se connecter</a> 
            </div> 
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block">Envoyer</button>
            </div>    
        </form>
        </div> 
    </div> 

    <br><br>


</section>





{% endblock content %}

src/templates/accounts/login.html
{% extends "base/base.html" %}

{% load static %}

{% block title %}
	Connexion
{% endblock title %}

{% block content %}


<section class="section-conten padding-y" style="min-height:84vh">

    {% if request.GET.command == 'verification' %}

      <div class="container mx-auto alert alert-info text-center" role="alert" style="max-width: 1024px; margin-top:100px;">

        <p>
              Notre équipe vous remercie de votre inscription sur le site <strong>E-Makeety</strong>. <br>
              Les instructions d'activation de votre compte ont été envoyées à l'adresse suivante [{{ request.GET.email }}]
        </p>
      <br><br>
      <p>Avez-vous deja activé votre compte?<br>
      <small><a href="{% url 'accounts:login' %}">Se connecter</a></small>
       </p>
      </div>

  {% else %}

  
    <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
        <div class="card-body">
        <h4 class="card-title mb-4">Se connecter</h4>

        {% include "includes/alerts.html" %}
        
        <form method="POST" action="{% url 'accounts:login' %}">
          {% csrf_token %}
            <!-- <a href="#" class="btn btn-facebook btn-block mb-2"> <i class="fab fa-facebook-f"></i> &nbsp;   Facebook</a>
            <a href="#" class="btn btn-google btn-block mb-4"> <i class="fab fa-google"></i> &nbsp; Google</a>
     -->

              <div class="form-group">
                  <div class="input-group">
                  <div class="input-group-prepend">
                      <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
                  </div>
                    <input type="email" name="email" class="form-control" placeholder="Votre adresse email" required="required">
              </div>
              </div>  
              <div class="form-group">
                  <div class="input-group">
                  <div class="input-group-prepend">
                      <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                  </div>
                    <input type="password" name="password" class="form-control" placeholder="Mot de passe" required="required">
              </div>
              </div>  

            
            <div class="form-group">
              <a href="{% url 'accounts:forgot_password' %}" class="float-right">Mot de passe oublié?</a> 
            </div> 
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block">Se connecter</button>
            </div>    
        </form>
        </div> 
    </div> 

    <p class="text-center mt-4">Vous n'avez pas de compte? <a href="{% url 'accounts:register' %}">S'inscrire</a></p>
    <br><br>

  {% endif %}


</section>




	
{% endblock content %}

src/templates/accounts/register.html
{% extends "base/base.html" %}

{% load static %}

{% block title %}
	Inscription
{% endblock title %}

{% block content %}
	
<section class="section-content padding-y">

	<div class="card mx-auto" style="max-width:520px; margin-top:40px;">
      <article class="card-body">
		<header class="mb-4"><h4 class="card-title">S'inscrire</h4></header>

		{% include 'includes/alerts.html' %}
		
		<form action="{% url 'accounts:register' %}" method="POST">
			{% csrf_token %}
				<div class="form-row">
					<div class="col form-group">
						<label>Nom</label>
					  	{{ form.first_name }}
					</div> 
					<div class="col form-group">
						<label>Prenom</label>
					  	{{ form.last_name }}
					</div>
				</div>
				<div class="form-group">
					<label>Email</label>
					{{ form.email }}
						<small class="form-text text-muted">Tenir secret votre adresse email.</small>
				</div> 
<!-- 
				<div class="form-row">
					<div class="form-group col-md-6">
					  <label>Téléphone</label>
					  {{ form.phone }}
					</div> 
				</div>  -->

				<div class="form-row">
					<div class="form-group col-md-6">
						<label>Mot de passe</label>
					    {{ form.password }}
					</div> 
					<div class="form-group col-md-6">
						<label>Confirmer votre mot de passe</label>
					    {{ form.confirm_password }}
					</div> 
				</div>
			    <div class="form-group">
			        <button type="submit" class="btn btn-primary btn-block">S'inscrire  </button>
			    </div>     
         
			</form>
		</article>
    </div> 
    <p class="text-center mt-4">Avez-vous déjà un compte? <a href="{% url 'accounts:login' %}">Se connecter</a></p>
    <br><br>
</section>



{% endblock content %}

src/templates/accounts/reset.html
{% extends "base/base.html" %}

{% load static %}

{% block title %}
  Nouveau mot de passe
{% endblock title %}

{% block content %}

<section class="section-conten padding-y" style="min-height:84vh">

  
    <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
        <div class="card-body">
        <h4 class="card-title mb-4">Nouveau mot de passe</h4>

        {% include "includes/alerts.html" %}
        
        <form method="POST" action="{% url 'accounts:reset_password' %}">
          {% csrf_token %}
    

              <div class="form-group">
                  <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                    </div>
                    <input type="password" name="password" class="form-control" placeholder="Votre nouveau mot de passe" required="required">
                   </div>
              </div>  

              <div class="form-group">
                  <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                    </div>
                    <input type="password" name="password2" class="form-control" placeholder="Confirmer votre nouveau mot de passe" required="required">
                   </div>
              </div>  

            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block">Réinitialiser</button>
            </div>    
        </form>
        </div> 
    </div> 

    <br><br>


</section>





  
{% endblock content %}

src/templates/accounts/reset_password_email.html
{% autoescape off %}
Bonjour, {{user.first_name|capfirst}}

Quelqu'un a demandé à réinitialiser votre mot de passe sur le site {{domain}}.
cliquer sur le lien ci-dessous pour suivre les instructions de réinitialisation de votre mot de passe

http://{{domain}}{% url 'accounts:reset_password_validate' uidb64=uid token=token  %}
    
Si vous n'êtes pas à l'origine de cette action veuillez ignorer ce message.
{% endautoescape %}